name = "anilist-sync"
main = "worker-prime-fetcher.js"
compatibility_date = "2024-12-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "0 */6 * * *",
  "0 */12 * * *"
]
